// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6wQZKhl4W6VwA6xY1S_XgwqSMz0Jtkew',
    appId: '1:742317270391:web:f61151dc349e4780e36d72',
    messagingSenderId: '742317270391',
    projectId: 'parolayoneticisi-c1387',
    authDomain: 'parolayoneticisi-c1387.firebaseapp.com',
    storageBucket: 'parolayoneticisi-c1387.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxjvhO1hnzKxtLBF76xozyHJA51ZhcB7g',
    appId: '1:742317270391:android:afbc7e8e0168f45ee36d72',
    messagingSenderId: '742317270391',
    projectId: 'parolayoneticisi-c1387',
    storageBucket: 'parolayoneticisi-c1387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfh2-Os_RIkMsqzmTUz1GK_ogvW8Kq7WM',
    appId: '1:742317270391:ios:3e5dcc9a24da8aa9e36d72',
    messagingSenderId: '742317270391',
    projectId: 'parolayoneticisi-c1387',
    storageBucket: 'parolayoneticisi-c1387.firebasestorage.app',
    iosBundleId: 'com.parolayoneticisiv2.parolaYoneticisiV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfh2-Os_RIkMsqzmTUz1GK_ogvW8Kq7WM',
    appId: '1:742317270391:ios:3e5dcc9a24da8aa9e36d72',
    messagingSenderId: '742317270391',
    projectId: 'parolayoneticisi-c1387',
    storageBucket: 'parolayoneticisi-c1387.firebasestorage.app',
    iosBundleId: 'com.parolayoneticisiv2.parolaYoneticisiV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6wQZKhl4W6VwA6xY1S_XgwqSMz0Jtkew',
    appId: '1:742317270391:web:2a3edd84ef347047e36d72',
    messagingSenderId: '742317270391',
    projectId: 'parolayoneticisi-c1387',
    authDomain: 'parolayoneticisi-c1387.firebaseapp.com',
    storageBucket: 'parolayoneticisi-c1387.firebasestorage.app',
  );
}
